### ISSUE TITLE
Crash laceration effect

### ISSUE THREAD

**Issue by someaddons** [Magistu/Knightly-Armory#16]
https://gist.github.com/someaddons/0c8b42683f35adb0d797873ddb6e8482

Crashes on sth with a mob effect

**Comment by Raycoms** [comment]
https://gist.github.com/Raycoms/3d991fc42458255e43fd1108e051a807

**Comment by izofar** [comment]
I got a crash log from a user of my my mod, Bygone Nether, that seems to indicate you don't register your laceration effect properly: https://pastebin.com/raw/VqcNGWV3. Looking at how you register your effect in the LacerationEffect class, you'd be much better off using DeferredRegister like in the following example: https://gist.github.com/Kaupenjoe/1f59e98da34bb16c48c41bd2980c9d57
