### ISSUE TITLE
[1.19.2] Dedicated server crash - java.lang.IllegalArgumentException: No delegate exists for value com.magistuarmory.effects.LacerationEffect

### ISSUE THREAD

**Issue by ProsperCraft** [Magistu/Knightly-Armory#18]
Crashlog-
https://gist.githubusercontent.com/ProsperCraft/fbde0d63fed633e3bd40d27331f27702/raw/072a16912efc443aa59475ff15224777698449bb/gistfile1.txt

Latest Log
https://gist.githubusercontent.com/ProsperCraft/c22dbee3a51f7162ec790430e0733c34/raw/db2857f995c161fc2f682b30706d9d7a5c4d67db/gistfile1.txt

[1.19.x]-Epic-Knights-Armor-and-Weapons-6.6v.jar

**Comment by ProsperCraft** [comment]
https://gist.githubusercontent.com/ProsperCraft/b2fd9fded07f0fcfd55cfa9be08f1d76/raw/13fafd60aa75f15ec748ee5d46bd018ffa832081/gistfile1.txt

Here is another dedicated server crash.

**Comment by ColdTearsYY** [comment]
Same question.server crashed.A wither skeleton with armors from this mod hit me and my server crashed.
debug.log:https://gist.github.com/ColdTearsYY/ecce162261047963c80d7c1c985780f2

**Comment by Dashcamp** [comment]
Similar to ColdTearsYY, I also met similar problem with a wither skeleton wearing armor from this mod. I have also posted this on discord and curseforge page just in case.

crash log:
https://gist.github.com/Dashcamp/8acd627f40c8c09abc04d6642ce89cd3

**Comment by Sekuraz** [comment]
In my experience it happens when I look at the wither skeleton.
https://bytebin.lucko.me/hoLQkUzreS

**Comment by AubthurYoung** [comment]
Yes! It happened on my server too!
I'm loading a wither skeleton

[crash-2022-10-18_15.01.17-fml.txt](https://github.com/Magistu/Knightly-Armory/files/9967138/crash-2022-10-18_15.01.17-fml.txt)
