### ISSUE TITLE
Realistic Horse Genetics and Epic Knights

### ISSUE THREAD

**Issue by Maltshakes** [Magistu/Knightly-Armory#23]
I'm working on adding compat between Realistic Horse Genetics and Epic Knights, though now I'm realizing Epic Knights is All Rights Reserved. Before I proceed further with adjusting the armors and caparisons to fit the RHG horses I want to check in. Would I be allowed to create compat between the two mods?

**Comment by Magistu** [comment]
yes, you're allowed
