### ISSUE TITLE
Loot Tables spawning multiple horse armor in every chest

### ISSUE THREAD

**Issue by Damdrara** [Magistu/Knightly-Armory#25]
![Example](https://cdn.discordapp.com/attachments/1038099450381479988/1069026783334252594/image.png)

Assuming this isn't intended, I'm guessing you misunderstood how the "weight" property works. To my understanding, it's not a chance (x in 100), but a ratio (x in sum-of-all-entries). 

So if you have a weight of 5 for chainmail_horse_armor, and a weight of 3 for barding, and nothing else, that means it'll always add one of them, and chainmail slightly more often than barding. and combined with your multiple rolls in each table means it'll always add multiple bardings.

You might wanna add the entry
```
{
  "type": "empty",
  "weight": 92
}
```

...to all these loot tables to fix this. Then it'll actually behave like a percentage, as I believe you intended. And even then, I'd reconsider the multiple rolls, because there's really no reason why a ruined portal chest should ever have up to 8 horse armors in there, imho.

If I'm wrong and this works exactly as intended, then.. please reconsider that anyway. This is just way too much horse armor!

**Comment by Magistu** [comment]
thank you, seems to be fixed
