### ISSUE TITLE
[1.18.2] Attribute bonuses of armour items in the player's hotbar are granted despite not having them equipped

### ISSUE THREAD

**Issue by Dyshonored** [Magistu/Knightly-Armory#6]
**Issue description**
When playing with this mod on minecraft 1.18.2, attribute bonuses of armour items in the player's hotbar are granted despite not having them equipped

**Steps to reproduce**
Add this mod to the forge mod loader
acquire some armour items in-game
place armour item in hotbar (but not equipping them)
Use mouse wheel to select the armour item in hotbar without equipping them
notice the player armour attribute increases permanently despite not having equipped any of the selected armour item
This persists sometimes even if the player equips and then unequips the previously selected item
Dying resets the armour value to 0 (as players will not respawn with anything), but selecting an armour item in the above manner causes the glitch again

Also my forge version is 40.1.0 in case that helps. Cheers!

**Comment by BastiOFF** [comment]
I'm having the same problem. please fix this !

**Comment by BastiOFF** [comment]
When do you fix it..?

**Comment by BastiOFF** [comment]
hello..?
